angular.module('app').service('storyService', function() {

  this.chapters = [
    {
      id: 'c1_3o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "two({id: 'c2a_2o'})",
      button2lnk: "two({id: 'c2b_2o'})",
      button3lnk: "two({id: 'c2c_2o'})"
    },
    {
      id: 'c2a_2o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'c3a_1o'})",
      button2lnk: "fight({id: 'c3b_f'})",
      button3lnk: ''
    },
    {
      id: 'c2b_2o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'c3c_f'})",
      button2lnk: "two({id: 'c3d_2o'})",
      button3lnk: ''
    },
    {
      id: 'c2c_2o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "two({id: 'c3e_2o'})",
      button2lnk: "fight({id: 'c3f_f'})",
      button3lnk: ''
    },
    {
      id: 'c3a_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c3b_f',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'c4a_1o'})",
      button2lnk: "one({id: 'c4b_1o'})",
      button3lnk: ''
    },
    {
      id: 'c3c_f',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'c4c_1o'})",
      button2lnk: "one({id: 'c4d_1o'})",
      button3lnk: ''
    },
    {
      id: 'c3d_2o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'c4e_f'})",
      button2lnk: "one({id: 'c4f_1o'})",
      button3lnk: ''
    },
    {
      id: 'c3e_2o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'c4g_1o'})",
      button2lnk: "fight({id: 'c4h_f'})",
      button3lnk: ''
    },
    {
      id: 'c3f_f',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'c4i_1o'})",
      button2lnk: "one({id: 'c4j_1o'})",
      button3lnk: ''
    },
    {
      id: 'c4a_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5a_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4b_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5a_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4c_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5b_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4d_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4e_f',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4f_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4g_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4h_f',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4i_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4j_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c5a_3o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'c6a_f'})",
      button2lnk: "one({id: 'c6b_1o'})",
      button3lnk: "one({id: 'c6c_1o'})"
    },
    {
      id: 'c5b_3o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'c6a_f'})",
      button2lnk: "one({id: 'c6b_1o'})",
      button3lnk: "one({id: 'c6c_1o'})"
    },
    {
      id: 'c5c_3o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'c6a_f'})",
      button2lnk: "one({id: 'c6b_1o'})",
      button3lnk: "one({id: 'c6c_1o'})"
    },
    {
      id: 'c6a_f',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c7_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c6b_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c7_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c6c_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c7_3o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'c8a_1o'})",
      button2lnk: "one({id: 'c8b_1o'})",
      button3lnk: "one({id: 'c8c_1o'})"
    },
    {
      id: 'c8a_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c8b_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c8c_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd1_3o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "two({id: 'd2a_2o'})",
      button2lnk: "two({id: 'd2b_2o'})",
      button3lnk: "two({id: 'd2c_2o'})"
    },
    {
      id: 'd2a_2o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'd3a_f'})",
      button2lnk: "two({id: 'd3b_2o'})",
      button3lnk: ''
    },
    {
      id: 'd2b_2o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "two({id: 'd3c_2o'})",
      button2lnk: "fight({id: 'd3d_f'})",
      button3lnk: ''
    },
    {
      id: 'd2c_2o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'd3e_f'})",
      button2lnk: "one({id: 'd3f_1o'})",
      button3lnk: ''
    },
    {
      id: 'd3a_f',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'd4a_f'})",
      button2lnk: "one({id: 'd4b_1o'})",
      button3lnk: ''
    },
    {
      id: 'd3b_2o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd4c_1o'})",
      button2lnk: "fight({id: 'd4d_f'})",
      button3lnk: ''
    },
    {
      id: 'd3c_2o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd4e_1o'})",
      button2lnk: "fight({id: 'd4f_f'})",
      button3lnk: ''
    },
    {
      id: 'd3d_f',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd4g_1o'})",
      button2lnk: "one({id: 'd4h_1o'})",
      button3lnk: ''
    },
    {
      id: 'd3e_f',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd4i_1o'})",
      button2lnk: "one({id: 'd4j_f'})",
      button3lnk: ''
    },
    {
      id: 'd3f_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4a_f',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5a_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4b_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4c_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5a_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4d_f',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5a_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4e_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4f_f',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5b_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4g_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4h_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4i_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4j_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd5a_3o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd6a_1o'})",
      button2lnk: "one({id: 'd6b_1o'})",
      button3lnk: "fight({id: 'd6c_f'})"
    },
    {
      id: 'd5b_3o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd6a_1o'})",
      button2lnk: "one({id: 'd6b_1o'})",
      button3lnk: "fight({id: 'd6c_f'})"
    },
    {
      id: 'd5c_3o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd6a_1o'})",
      button2lnk: "one({id: 'd6b_1o'})",
      button3lnk: "fight({id: 'd6c_f'})"
    },
    {
      id: 'd6a_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd7_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd6b_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd6c_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd7_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd7_3o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd8a_1o'})",
      button2lnk: "one({id: 'd8b_1o'})",
      button3lnk: "one({id: 'd8c_1o'})"
    },
    {
      id: 'd8a_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd8b_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd8c_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w1_3o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "two({id: 'w2a_2o'})",
      button2lnk: "two({id: 'w2b_2o'})",
      button3lnk: "two({id: 'w2c_2o'})"
    },
    {
      id: 'w2a_2o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'w3a_f'})",
      button2lnk: "two({id: 'w3b_2o'})",
      button3lnk: ''
    },
    {
      id: 'w2b_2o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'w3c_f'})",
      button2lnk: "one({id: 'w3d_1o'})",
      button3lnk: ''
    },
    {
      id: 'w2c_2o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'w3e_f'})",
      button2lnk: "two({id: 'w3f_2o'})",
      button3lnk: ''
    },
    {
      id: 'w3a_f',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w4a_1o'})",
      button2lnk: "one({id: 'w4b_1o'})",
      button3lnk: ''
    },
    {
      id: 'w3b_2o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w4c_1o'})",
      button2lnk: "fight({id: 'w4d_f'})",
      button3lnk: ''
    },
    {
      id: 'w3c_f',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w4e_1o'})",
      button2lnk: "one({id: 'w4f_1o'})",
      button3lnk: ''
    },
    {
      id: 'w3d_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w3e_f',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w4g_1o'})",
      button2lnk: "one({id: 'w4h_1o'})",
      button3lnk: ''
    },
    {
      id: 'w3f_2o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w4i_1o'})",
      button2lnk: "fight({id: 'w4j_f'})",
      button3lnk: ''
    },
    {
      id: 'w4a_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5a_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4b_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4c_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4d_f',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5b_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4e_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5b_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4f_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5b_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4g_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4h_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4i_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4j_f',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w5a_3o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w6a_1o'})",
      button2lnk: "fight({id: 'w6b_f'})",
      button3lnk: "one({id: 'w5c_1o'})"
    },
    {
      id: 'w5b_3o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w6a_1o'})",
      button2lnk: "fight({id: 'w6b_f'})",
      button3lnk: "one({id: 'w5c_1o'})"
    },
    {
      id: 'w5c_3o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w6a_1o'})",
      button2lnk: "fight({id: 'w6b_f'})",
      button3lnk: "one({id: 'w5c_1o'})"
    },
    {
      id: 'w6a_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w6b_f',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w7_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w6c_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w7_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w7_3o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w8a_1o'})",
      button2lnk: "one({id: 'w8b_1o'})",
      button3lnk: "one({id: 'w8c_1o'})"
    },
    {
      id: 'w8a_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w8b_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w8c_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    }
  ]


})
