angular.module('app').service('storyService', function() {

  this.chapters = [
    {
      id: 'c1_3o',
      character: 'Cleric',
      story1: "The mountain wind chills your bones as you emerge from the Temple of Talos and you gather your robes around you. Two years have passed quickly and you must return in haste to your village. Talos has made known to you his pleasure in your service and has granted you a portion of his power. Whatever is coming threatens his hold on this part of the world as well as your people’s.",
      story2: "After making your way down the well-worn trail to the base of the mountain, you arrive at a crossroads. Straight ahead is a forest. The trees are thick and the path is narrow. Rumors say travelers have disappeared inside, but it offers the fastest walking route north. To the right is a wide road around the forest. West leads to a village where you can arrange passage on a ship. This may see you to your village the soonest, but the ocean can be dangerous. Where will you go?",
      sideimg: '',
      topimg: '',
      button1txt: 'The forest sounds nice',
      button2txt: 'A well-worn road offers the safest bet',
      button3txt: 'Time to set sail. No time for walking',
      button1lnk: "two({id: 'c2a_2o'})",
      button2lnk: "two({id: 'c2b_2o'})",
      button3lnk: "two({id: 'c2c_2o'})"
    },
    {
      id: 'c2a_2o',
      character: 'Cleric',
      story1: "You have been walking warily through the forest for what seems like hours. Paths have split and converged several times and you have long since lost track of which direction is north. You are lost. You rest on a boulder to think, pray, and eat. As you are bringing out some bread and cheese, you hear a rustling in a nearby thicket.",
      story2: "Your instincts say to run, but your curiosity begs to you stay.",
      sideimg: '',
      topimg: '',
      button1txt: 'Get away as fast as you can',
      button2txt: 'Stay and see what is coming',
      button3txt: 'option 3',
      button1lnk: "one({id: 'c3a_1o'})",
      button2lnk: "fight({id: 'c3b_f'})",
      button3lnk: ''
    },
    {
      id: 'c2b_2o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'c3c_f'})",
      button2lnk: "two({id: 'c3d_2o'})",
      button3lnk: ''
    },
    {
      id: 'c2c_2o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "two({id: 'c3e_2o'})",
      button2lnk: "fight({id: 'c3f_f'})",
      button3lnk: ''
    },
    {
      id: 'c3a_1o',
      character: 'Cleric',
      story1: "Running, panting, tripping, you race through the forest. The rustling hasn’t stopped. In fact, it’s increased. Calling on Talos, you prepare a spell and turn just in time to see the hobgoblin slice your knees. Your spell is cut short and your life is as well. The creature gurgles in what sounds like laughter as more emerge from behind trees.",
      story2: "As the world fades to black, you feel a rumbling in the back of your mind. Talos is displeased.",
      died: "You have died",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c3b_f',
      character: 'Cleric',
      story1: "After laying waste to the creature, you notice tracks. Following the tracks may not be the wisest thing to do, but you are running out of options. The tracks lead off the path. Do you pray for direction or follow the tracks? Talos may be displeased if you call on him too often for things like directions.",
      story2: "",
      sideimg: '',
      topimg: '',
      button1txt: 'Follow the tracks',
      button2txt: 'Pray for guidance',
      button3txt: 'option 3',
      button1lnk: "one({id: 'c4a_1o'})",
      button2lnk: "one({id: 'c4b_1o'})",
      button3lnk: ''
    },
    {
      id: 'c3c_f',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'c4c_1o'})",
      button2lnk: "one({id: 'c4d_1o'})",
      button3lnk: ''
    },
    {
      id: 'c3d_2o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'c4e_f'})",
      button2lnk: "one({id: 'c4f_1o'})",
      button3lnk: ''
    },
    {
      id: 'c3e_2o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'c4g_1o'})",
      button2lnk: "fight({id: 'c4h_f'})",
      button3lnk: ''
    },
    {
      id: 'c3f_f',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'c4i_1o'})",
      button2lnk: "one({id: 'c4j_1o'})",
      button3lnk: ''
    },
    {
      id: 'c4a_1o',
      character: 'Cleric',
      story1: "You carefully follow the creature’s tracks until you come to the edges of what looks like a crude camp. Goblins, hobgoblins, and other creatures roam about and fight for food. You aren’t getting past them, and even if you could, you would still be lost. Perhaps through intuition, perhaps through divine inspiration, you come up with a plan.",
      story2: "Calling on Talos, you summon pealing thunder and a bolt of lightning that strikes a tree in the center of the camp, lighting the tree nearby encampments on fire. The creatures flee. You follow. It’s not long before they bolt out of the forest, bellowing their guttural screams. You wait for them to disperse and exit yourself. It’s dark, but you are finally able to get your bearings with a quick look at the stars. You are close now. Through some miracle, you have made your way north and the village should be just over the next ridge. The forest placed you much closer than it should have. Strange.",
      sideimg: '',
      topimg: '',
      button1txt: 'Almost home. Time to be hero.',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5a_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4b_1o',
      character: 'Cleric',
      story1: "As you call to Talos in supplication, you sense his frustration, but also his need for urgency. In this time of need, he grants you with a power not yet bestowed upon you and it makes you nervous. He wants you to speak with the dead.",
      story2: "The spell is successful and the creature you have just slain begins speaking in words you can understand. You demand to know the way out of the forest and it is forced to comply. Shuddering, you memorize the instructions relayed from the corpse and quickly proceed out of the forest. As you exit, you realize that your village is close, most likely, just over the next ridge, though by all accounts you should still days away.  No matter. Nothing to do but move forward.",
      sideimg: '',
      topimg: '',
      button1txt: 'Head to the village',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5a_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4c_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5b_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4d_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4e_f',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4f_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4g_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4h_f',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4i_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c4j_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c5a_3o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'c6a_f'})",
      button2lnk: "one({id: 'c6b_1o'})",
      button3lnk: "one({id: 'c6c_1o'})"
    },
    {
      id: 'c5b_3o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'c6a_f'})",
      button2lnk: "one({id: 'c6b_1o'})",
      button3lnk: "one({id: 'c6c_1o'})"
    },
    {
      id: 'c5c_3o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'c6a_f'})",
      button2lnk: "one({id: 'c6b_1o'})",
      button3lnk: "one({id: 'c6c_1o'})"
    },
    {
      id: 'c6a_f',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c7_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c6b_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'c7_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c6c_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c7_3o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'c8a_1o'})",
      button2lnk: "one({id: 'c8b_1o'})",
      button3lnk: "one({id: 'c8c_1o'})"
    },
    {
      id: 'c8a_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c8b_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'c8c_1o',
      character: 'Cleric',
      story1: "This is cleric story paragraph one.",
      story2: "This is cleric story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd1_3o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "two({id: 'd2a_2o'})",
      button2lnk: "two({id: 'd2b_2o'})",
      button3lnk: "two({id: 'd2c_2o'})"
    },
    {
      id: 'd2a_2o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'd3a_f'})",
      button2lnk: "two({id: 'd3b_2o'})",
      button3lnk: ''
    },
    {
      id: 'd2b_2o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "two({id: 'd3c_2o'})",
      button2lnk: "fight({id: 'd3d_f'})",
      button3lnk: ''
    },
    {
      id: 'd2c_2o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'd3e_f'})",
      button2lnk: "one({id: 'd3f_1o'})",
      button3lnk: ''
    },
    {
      id: 'd3a_f',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'd4a_f'})",
      button2lnk: "one({id: 'd4b_1o'})",
      button3lnk: ''
    },
    {
      id: 'd3b_2o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd4c_1o'})",
      button2lnk: "fight({id: 'd4d_f'})",
      button3lnk: ''
    },
    {
      id: 'd3c_2o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd4e_1o'})",
      button2lnk: "fight({id: 'd4f_f'})",
      button3lnk: ''
    },
    {
      id: 'd3d_f',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd4g_1o'})",
      button2lnk: "one({id: 'd4h_1o'})",
      button3lnk: ''
    },
    {
      id: 'd3e_f',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd4i_1o'})",
      button2lnk: "one({id: 'd4j_f'})",
      button3lnk: ''
    },
    {
      id: 'd3f_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4a_f',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5a_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4b_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4c_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5a_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4d_f',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5a_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4e_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4f_f',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5b_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4g_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4h_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4i_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd4j_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'd5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd5a_3o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd6a_1o'})",
      button2lnk: "one({id: 'd6b_1o'})",
      button3lnk: "fight({id: 'd6c_f'})"
    },
    {
      id: 'd5b_3o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd6a_1o'})",
      button2lnk: "one({id: 'd6b_1o'})",
      button3lnk: "fight({id: 'd6c_f'})"
    },
    {
      id: 'd5c_3o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd6a_1o'})",
      button2lnk: "one({id: 'd6b_1o'})",
      button3lnk: "fight({id: 'd6c_f'})"
    },
    {
      id: 'd6a_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd7_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd6b_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd6c_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd7_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd7_3o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'd8a_1o'})",
      button2lnk: "one({id: 'd8b_1o'})",
      button3lnk: "one({id: 'd8c_1o'})"
    },
    {
      id: 'd8a_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd8b_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'd8c_1o',
      character: 'Druid',
      story1: "This is druid story paragraph one.",
      story2: "This is druid story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w1_3o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "two({id: 'w2a_2o'})",
      button2lnk: "two({id: 'w2b_2o'})",
      button3lnk: "two({id: 'w2c_2o'})",
      bar: "wizard-bar"
    },
    {
      id: 'w2a_2o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'w3a_f'})",
      button2lnk: "two({id: 'w3b_2o'})",
      button3lnk: ''
    },
    {
      id: 'w2b_2o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'w3c_f'})",
      button2lnk: "one({id: 'w3d_1o'})",
      button3lnk: ''
    },
    {
      id: 'w2c_2o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "fight({id: 'w3e_f'})",
      button2lnk: "two({id: 'w3f_2o'})",
      button3lnk: ''
    },
    {
      id: 'w3a_f',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w4a_1o'})",
      button2lnk: "one({id: 'w4b_1o'})",
      button3lnk: ''
    },
    {
      id: 'w3b_2o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w4c_1o'})",
      button2lnk: "fight({id: 'w4d_f'})",
      button3lnk: ''
    },
    {
      id: 'w3c_f',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w4e_1o'})",
      button2lnk: "one({id: 'w4f_1o'})",
      button3lnk: ''
    },
    {
      id: 'w3d_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w3e_f',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w4g_1o'})",
      button2lnk: "one({id: 'w4h_1o'})",
      button3lnk: ''
    },
    {
      id: 'w3f_2o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w4i_1o'})",
      button2lnk: "fight({id: 'w4j_f'})",
      button3lnk: ''
    },
    {
      id: 'w4a_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5a_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4b_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4c_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4d_f',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5b_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4e_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5b_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4f_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5b_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4g_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4h_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4i_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w4j_f',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "three({id: 'w5c_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w5a_3o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w6a_1o'})",
      button2lnk: "fight({id: 'w6b_f'})",
      button3lnk: "one({id: 'w5c_1o'})"
    },
    {
      id: 'w5b_3o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w6a_1o'})",
      button2lnk: "fight({id: 'w6b_f'})",
      button3lnk: "one({id: 'w5c_1o'})"
    },
    {
      id: 'w5c_3o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w6a_1o'})",
      button2lnk: "fight({id: 'w6b_f'})",
      button3lnk: "one({id: 'w5c_1o'})"
    },
    {
      id: 'w6a_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w6b_f',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w7_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w6c_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w7_3o'})",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w7_3o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'option 1',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "one({id: 'w8a_1o'})",
      button2lnk: "one({id: 'w8b_1o'})",
      button3lnk: "one({id: 'w8c_1o'})"
    },
    {
      id: 'w8a_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w8b_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    },
    {
      id: 'w8c_1o',
      character: 'Wizard',
      story1: "This is wizard story paragraph one.",
      story2: "This is wizard story paragraph two.",
      sideimg: '',
      topimg: '',
      button1txt: 'Start Over',
      button2txt: 'option 2',
      button3txt: 'option 3',
      button1lnk: "home",
      button2lnk: "",
      button3lnk: ''
    }
  ]


})
